Update proof
Fails
```
Error: Trying to call acir_proofs_init_proving_key resulted in an error

Caused by:
   0: RuntimeError: out of bounds memory access
   1: heap_get_oob
```